
all:
	make -C src/dvita-foundation-framework $@

build:
	make -C src/dvita-foundation-framework $@

test:
	make -C src/dvita-foundation-framework.tests $@

clean:
	make -C src/dvita-foundation-framework $@
	make -C src/dvita-foundation-framework.tests $@

.PHONY: all build test clean

.SILENT: clean 
